### ISSUE TITLE
Git-based page histories plugin does not work

### ISSUE THREAD

**Issue by get1024** [nolebase/integrations#194]
The plug-in is configured according to the tutorial in the documentation, but does not work after deployment。

config.mts
![image](https://github.com/nolebase/integrations/assets/98867071/7d5851b0-12ef-4510-995f-dae15fdb0703)
![image](https://github.com/nolebase/integrations/assets/98867071/95567bfc-d2ad-44da-bc85-44d7eb86e108)

docs\.vitepress\theme\index.ts
![image](https://github.com/nolebase/integrations/assets/98867071/44c0028a-fb6e-4135-82c3-6de50a951311)
![image](https://github.com/nolebase/integrations/assets/98867071/2ad43c24-7bf6-46be-a4e5-c9cc48d4e0ca)

and the result on my website is as:
![image](https://github.com/nolebase/integrations/assets/98867071/4860c651-2d2c-4b30-934b-765ebd35b0dc)

Has anyone succeeded in following the documentation? Is there anything wrong with my configuration process? Ask for advice

**Comment by get1024** [comment]
I currently deploy through the github action, deploy.yml is the default configuration provided in the vitepress documentation

**Comment by nekomeowww** [comment]
> I currently deploy through the github action, deploy.yml is the default configuration provided in the vitepress documentation

Can you see the git logs with development server (`pnpm run docs:dev`)

**Comment by get1024** [comment]
nope
the content of my deploy.yml as follows:

```
# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      # - uses: pnpm/action-setup@v3 # 如果使用 pnpm，请取消注释
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # 或 pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci # 或 pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: npm run docs:build # 或 pnpm docs:build / yarn docs:build / bun run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

whether run `pnpm run docs:dev` or submit it to the repository, none of my sites show git logs💔
