### ISSUE TITLE
使用侧边聚光灯之后，原 Vitepress 标题 ‘#’ 提示和聚光灯条重合

### ISSUE THREAD

**Issue by 6get-xiaofan** [nolebase/integrations#307]
一级标题的 ‘#’ 会出现重合现象，目前我的解决办法是隐藏 Vitepress 的这个 ‘#’

```css
.header-anchor {
  display: none !important;
} 
```

![动画](https://github.com/user-attachments/assets/58e99896-a29e-4ce8-a2c3-fdc3cac1c3de)
